/**
 * Single source of truth for company-specific values.
 *
 * Every value can be overridden per-instance with a VITE_COMPANY_* env var.
 * With no env vars set, defaults produce the AMP instance exactly as before —
 * so our own deployment needs zero configuration changes.
 *
 * To stand up a new customer instance, set these in the instance's .env /
 * Netlify environment; do not edit this file.
 */

const env = import.meta.env;

/** Vite types env values as string | boolean; only accept non-empty strings. */
const str = (value: unknown, fallback: string): string =>
  typeof value === "string" && value ? value : fallback;

/** Split a comma-separated env var into a trimmed string array. */
const list = (value: unknown, fallback: string[]): string[] =>
  typeof value === "string" && value
    ? value.split(",").map((s) => s.trim()).filter(Boolean)
    : fallback;

export const companyConfig = {
  /** Short product/company display name (page titles, UI). */
  name: str(env.VITE_COMPANY_NAME, "AMP"),
  /** Full company name used on documents (proposals, POs, reports). */
  fullName: str(env.VITE_COMPANY_FULL_NAME, "AMP Quality Energy Services"),
  /** Legal entity name used in contract/terms language. */
  legalName: str(env.VITE_COMPANY_LEGAL_NAME, "AMP LLC"),

  /** Main phone number as printed on documents. */
  phone: str(env.VITE_COMPANY_PHONE, "(256) 513-8255"),
  /** One-line mailing address for document footers. */
  addressLine: str(env.VITE_COMPANY_ADDRESS, "P.O. Box 1725 Decatur, AL 35602"),
  /** Physical ship-to address (default on vendor purchase orders). */
  shipToAddress: str(env.VITE_COMPANY_SHIPTO_ADDRESS, "616 Church St. NE"),
  shipToCity: str(env.VITE_COMPANY_SHIPTO_CITY, "Decatur"),
  shipToState: str(env.VITE_COMPANY_SHIPTO_STATE, "AL"),
  shipToZip: str(env.VITE_COMPANY_SHIPTO_ZIP, "35601"),
  /** Footer variant with pipe separators (proposal footer). */
  addressFooter:
    str(env.VITE_COMPANY_ADDRESS_FOOTER, "P.O. Box 1725 | Decatur, Alabama 35602"),

  /** Where vendors send invoices. */
  accountingEmail:
    str(env.VITE_COMPANY_ACCOUNTING_EMAIL, "accounting@ampqes.com"),
  /** Where customers send purchase orders. */
  purchaseOrdersEmail:
    str(env.VITE_COMPANY_PO_EMAIL, "purchaseorders@ampqes.com"),
  /** Support/contact email shown on EULA, Privacy, login errors. */
  supportEmail: str(env.VITE_COMPANY_SUPPORT_EMAIL, "support@ampos.io"),

  /** Public website domain (shown on report footers). */
  websiteDomain: str(env.VITE_COMPANY_WEBSITE, "ampqes.com"),
  /** Product site URL (EULA/Privacy pages). */
  productUrl: str(env.VITE_COMPANY_PRODUCT_URL, "https://ampos.io"),

  /** Email domains allowed to sign up / treated as employees. */
  allowedEmailDomains: list(env.VITE_COMPANY_EMAIL_DOMAINS, [
    "@ampqes.com",
    "@cedsi.com",
  ]),
  /** Emails that always get full admin access. */
  superuserEmails: list(env.VITE_COMPANY_SUPERUSER_EMAILS, [
    "john.chambers@ampqes.com",
    "jack.lyons@ampqes.com",
  ]),

  /** Default proposal signer. */
  signerName: str(env.VITE_COMPANY_SIGNER_NAME, "Brian Rodgers"),
  signerTitle: str(env.VITE_COMPANY_SIGNER_TITLE, "Chief Executive Officer"),

  /** Brand color (hex) and its darker hover companion. */
  brandColor: str(env.VITE_COMPANY_BRAND_COLOR, "#f26722"),
  brandColorDark: str(env.VITE_COMPANY_BRAND_COLOR_DARK, "#e55611"),

  /** Logo/favicon paths (files live in /public; swap files per instance). */
  logoPath: str(env.VITE_COMPANY_LOGO, "/ampOS-logo.png"),
  faviconPath: str(env.VITE_COMPANY_FAVICON, "/ampOS-favicon.svg"),

  /** Base URL for offline-app installer downloads (GitHub Releases). */
  offlineReleaseBase:
    str(env.VITE_COMPANY_OFFLINE_RELEASE_BASE, "https://github.com/banjito/Active-Website-Software/releases/download/offline-v1.0.0"),

  /**
   * The HR handbook content is AMP-specific legal text. Buyer instances
   * should hide it (set VITE_COMPANY_SHOW_HR_HANDBOOK=false) until they
   * supply their own.
   */
  showHrHandbook: env.VITE_COMPANY_SHOW_HR_HANDBOOK !== "false",
} as const;

/** Brand hex values for JS contexts where CSS variables can't be used
 * (detached print/PDF documents, hex-with-alpha-suffix tricks).
 * `let` on purpose: applyBrandColorValues updates them when an admin-saved
 * theme loads, and ES module live bindings propagate to importers. */
export let BRAND_COLOR = companyConfig.brandColor;
export let BRAND_COLOR_DARK = companyConfig.brandColorDark;

const hexToRgbTriple = (hex: string): string => {
  const h = hex.replace("#", "");
  const n = parseInt(
    h.length === 3 ? h.split("").map((c) => c + c).join("") : h,
    16
  );
  return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`;
};

/**
 * Push a pair of brand colors into CSS variables on <html> so Tailwind's
 * `brand` palette and any `var(--brand)` styles pick them up.
 * Used at boot with the env/default colors and by the admin Website Theme
 * page for DB-saved overrides and live preview.
 */
export const applyBrandColorValues = (brand: string, dark: string): void => {
  BRAND_COLOR = brand;
  BRAND_COLOR_DARK = dark;
  const root = document.documentElement.style;
  root.setProperty("--brand", brand);
  root.setProperty("--brand-rgb", hexToRgbTriple(brand));
  root.setProperty("--brand-dark", dark);
  root.setProperty("--brand-dark-rgb", hexToRgbTriple(dark));
};

/** Apply the env/default brand colors. Call once at app boot (main.tsx). */
export const applyBrandColors = (): void =>
  applyBrandColorValues(BRAND_COLOR, BRAND_COLOR_DARK);

/** Darken a hex color by the given factor (0–1); used to derive the hover shade. */
export const darkenHex = (hex: string, factor = 0.12): string => {
  const h = hex.replace("#", "");
  const full = h.length === 3 ? h.split("").map((c) => c + c).join("") : h;
  const n = parseInt(full, 16);
  const scale = (v: number) => Math.max(0, Math.round(v * (1 - factor)));
  const [r, g, b] = [scale((n >> 16) & 255), scale((n >> 8) & 255), scale(n & 255)];
  return `#${((r << 16) | (g << 8) | b).toString(16).padStart(6, "0")}`;
};

/** Placeholder like "your@ampqes.com" built from the first allowed domain. */
export const emailPlaceholder = `your${companyConfig.allowedEmailDomains[0] || "@example.com"}`;

/** Regex matching an employee email on any allowed domain. */
export const employeeEmailRegex = new RegExp(
  `(${companyConfig.allowedEmailDomains
    .map((d) => d.replace(".", "\\."))
    .join("|")})$`,
  "i"
);

/**
 * Regex capturing first/last name from a first.last@<allowed-domain> email.
 * Match groups 1 and 2 are the first and last name.
 */
export const employeeNameEmailRegex = new RegExp(
  `^([a-z]+)\\.([a-z]+)(${companyConfig.allowedEmailDomains
    .map((d) => d.replace(".", "\\."))
    .join("|")})$`,
  "i"
);
